import { generateId } from '$lib/utils/id';
import type { UploadType } from './upload.types';
import { uploadFile } from './upload.utils';

export type ShareResult = {
	id: string | null;
	url: string | null;
};

/**
 * Shares plain text content by turning it into a File and uploading it.
 * Returns a share id (client-generated) and the public URL from the uploader.
 */
export async function uploadMap(content: string): Promise<ShareResult | null> {
	// This is a temporary id for the file not to be confused with the id generated by the api
	const tempId = generateId();
	const safeName = `${tempId}.grpl`;
	const file = new File([content], safeName, { type: 'text/plain' });
	const { id } = await uploadFile(file, 'file' satisfies UploadType);
	if (!id) return null;

	// Inject the current base URL for absolute share link
	const base = typeof window !== 'undefined' ? `${window.location.origin}` : ''; // fallback for server
	return { id, url: `${base}/share/${id}` };
}
